### ISSUE TITLE
CORS not implemented

### ISSUE THREAD

**Issue by gnomeontherun** [sosedoff/opentable#7]
Is it possible to implements CORS headers? It should only need one new header and it should be available put on all OPTIONS requests.

`Access-Control-Allow-Origin: *`

**Comment by gnomeontherun** [comment]
I'm not a ruby dev, but looking up how sinatra works something like this might do the trick.

````ruby
options "/*" do
  headers["Access-Control-Allow-Origin"] = "*"
end
````

**Comment by sosedoff** [comment]
done
