### ISSUE TITLE
Searching restaurant by name

### ISSUE THREAD

**Issue by cyzanfar** [sosedoff/opentable#9]
Hey,

Is there a way to search and get the restaurant ratings given the name of the restaurant:

I tried:
```
http://opentable.herokuapp.com/api/restaurants?name=%22antica%20pesa%22
```
but didn't get the answer I was hoping...

**Comment by sosedoff** [comment]
http://opentable.herokuapp.com/api/restaurants?name=antica%20pesa
no need for double quotes

**Comment by cyzanfar** [comment]
Perfect thanks!! 
now, I get a response without the ratings..
```
{
total_entries: 1,
per_page: 25,
current_page: 1,
restaurants: [
{
id: 95632,
name: "Antica Pesa",
address: "115 Berry Street",
city: "Brooklyn",
state: "NY",
area: "New York / Tri-State Area",
postal_code: "11211",
country: "US",
phone: "3477632635",
lat: 40.718872,
lng: -73.958754,
price: 3,
reserve_url: "http://www.opentable.com/single.aspx?rid=95632",
mobile_reserve_url: "http://mobile.opentable.com/opentable/?restId=95632",
image_url: "https://www.opentable.com/img/restimages/95632.jpg"
}
]
}
```
Is there a way to access the ratings?

**Comment by sosedoff** [comment]
which rating are you talking about ?

**Comment by cyzanfar** [comment]
The review ratings for a particular restaurant for example this one : http://www.opentable.com/antica-pesa

**Comment by sosedoff** [comment]
unfortunately, this data is not available

**Comment by cyzanfar** [comment]
For example, antica pesa has a rating of 4.5 / 5. I'd like to access that rating

**Comment by cyzanfar** [comment]
ok that's fine thanks!
